services:
  nextcloud-db:
    image: postgres:15-alpine
    container_name: nextcloud-db
    restart: always
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${PASSWORD}
    networks:
      - web_network

  nextcloud:
    image: nextcloud:28-apache # Versão 28 é muito estável
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ${DATA}:/var/www/html
    ports:
      - "8081:80"
    networks:
      - web_network

networks:
  web_network:
    external: true
