services:
  nextcloud-db:
    image: mariadb:10.11 # MariaDB é mais leve e simples de configurar que Postgres
    container_name: nextcloud-db
    restart: always
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - web_network

  nextcloud:
    image: nextcloud:fpm-alpine # Alpine Linux + FPM = A versão mais pequena possível
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
    volumes:
      - ${DATA}:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${PASSWORD}
    networks:
      - web_network

networks:
  web_network:
    external: true
