services:
  snappymail:
    image: ajanvier/snappymail:sha256-67ad258f91d4b8a2fe8ff7ceb543be2a81416e3e2b70ebd2c203ce2f8ba8e197
    container_name: snappymail
    restart: always
    networks:
      - web_network
    volumes:
      - ${DATA}:/snappymail/data
    environment:
      - TZ=Europe/Lisbon
      # Limite de upload de anexos (ex: 50MB)
      - PHP_UPLOAD_MAX_FILESIZE=50M
      - PHP_POST_MAX_SIZE=50M
    # A porta interna padrão é a 8888
    expose:
      - "8888"

networks:
  web_network:
    external: true

volumes:
  snappymail_data:
