services:
  rainloop:
    image: lscr.io/linuxserver/rainloop:latest
    container_name: rainloop
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ${DATA}:/config
    expose:
      - "80"
    ports:
      - "8888:80"
    networks:
      - web_network

networks:
  web_network:
    name: web_network
    driver: bridge
